### PR TITLE
add support for the fish shell

### PR DESCRIPTION
**Pull request by demian0311**
I have iTerm2 setup to use the fish shell.  It doesn't like the && operator from bash.  I added an optional configuration so that a user could specify the shell in their TermFile.  If they don't specify the shell we just use the && operator as before.

### CODE REVIEW

**Comment by demian0311** [comment]
Yeah that was my thought but I was surprised to find that it's not very easy to do:

https://unix.stackexchange.com/questions/220663/how-do-i-reliably-and-simply-get-the-current-shell-interpreter-name

In my own fish shell it actually reports bash with that command.  Maybe some leftover bash config I have sitting around.

I agree that it's worth it to keep the TermFile un-cluttered.  I'm up for working on that.  The code might get a _little_ clunky though.

I could see trying to look for something fish specific and inferring from those results.

fish
```
[I] demian@thor ~ [I]> type help | wc -l
     140
```

bash
```
22:10:19|demian@thor:~> type help | wc -l
       1
```

**Comment by briangonzalez** [comment]
Ok, then why not check the `FISH_VERSION`?

```
echo $FISH_VERSION
```

**Comment by demian0311** [comment]
Yeah, that looks like a legit approach.  I can look into that.

**Comment by demian0311** [comment]
```
[I] demian@thor ~/c/dotfiles (master) [I]> echo $FISH_VERSION
2.2.0
[I] demian@thor ~/c/dotfiles (master) [I]> irb
irb(main):001:0> `echo $FISH_VERSION`
=> "\n"
irb(main):002:0> `echo $SHELL`
=> "/bin/bash\n"

**Pull request closed without merging**
